project/views/auth.py
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user, UserMixin
import re

from ..models import User
from .. import db

auth = Blueprint('auth', __name__)


# Function to check if a password meets complexity requirements
def is_valid_password(password):
    message = """Your password must be have at least
                    8 characters long
                    1 uppercase & 1 lowercase character
                    1 number"""
    return bool(re.match(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$', password)), message


# Function to check if an email address is valid
def is_valid_email(email):
    return bool(re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', email))


@auth.route('/login')
def login():
    return render_template('authentication/login.html', user=current_user)


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()
    if user:
        if check_password_hash(user.password, password):
            flash('Logged in successfully!', category='success')
            login_user(user, remember=remember)
            current_user.last_login = datetime.utcnow()
            db.session.commit()
            return redirect(url_for('main.home'))
        else:
            flash('Incorrect password, try again.', category='error')
    else:
        flash('Email does not exist.', category='error')

    return redirect(url_for('auth.login'))


@auth.route('/signup')
def signup():
    return render_template('main/user_create.html', user=current_user)


@auth.route('/signup', methods=['GET', 'POST'])
def signup_post():
    if request.method == 'POST':
        # Get the data from the request body
        username = request.form.get('username')
        firstname = request.form.get('firstname')
        middlename = request.form.get('middlename')
        lastname = request.form.get('lastname')
        birthdate = request.form.get('birthdate')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        print(username, firstname, middlename, lastname, birthdate, email, password1, password2)

        # check if email has been used before
        user = User.query.filter_by(email=email).first()

        # if a user is found, we want to redirect back to signup page so user can try again
        if user:
            flash('Email address already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 3:
            flash('Username must be greater than 2 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif not is_valid_password(password1)[0]:
            flash(is_valid_password(password1)[1], category='error')
        elif not is_valid_email(email):
            flash('Invalid email format!', category='error')
        else:
            new_user = User(username=username, firstname=firstname, middlename=middlename, lastname=lastname,
                        birthdate=birthdate, email=email, password=generate_password_hash(password1, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            if not current_user:
                login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('main.home'))

    return redirect(url_for('auth.signup'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

project/views/main.py
from datetime import datetime, timedelta

from flask import render_template, request, url_for, redirect, flash, Blueprint
from flask_login import login_required, current_user
from ..models import User
from .. import db


main = Blueprint('main', __name__)


@main.route('/')
@login_required
def home():
    return render_template('main/home.html', user=current_user)


@main.route('/user/list')
@login_required
def user_list():
    users = User.query.all()
    return render_template('main/user_list.html', users=users, user=current_user)


@main.route('/user/create', methods=('GET', 'POST'))
@login_required
def user_create():
    return redirect(url_for('auth.signup_post'))


@main.route('/user/update/<int:idx>', methods=('GET', 'POST'))
@login_required
def user_update(idx):
    user = User.query.get_or_404(idx)
    if request.method == 'POST':
        username = request.form.get('username')
        firstname = request.form.get('firstname')
        middlename = request.form.get('middlename')
        lastname = request.form.get('lastname')
        birthdate = request.form.get('birthdate')
        email = request.form.get('email')

        print(username,
        firstname,
        middlename,
        lastname,
        birthdate,
        email)

        user.username = username
        user.firstname = firstname
        user.middlename = middlename
        user.lastname = lastname
        user.birthdate = birthdate
        user.email = email

        db.session.add(user)
        db.session.commit()
        flash('User data updated successfully.', category='success')
        return redirect(url_for('main.user_list'))

    return render_template('main/user_update.html', user=user)


@main.post('/user/delete/<int:id>')
@login_required
def user_delete(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('main.home'))


@main.route('/onlineusers', methods=('GET', 'POST'))
@login_required
# @admin_required
def online_users():
    online_users = []
    users = User.query.all()
    for user in users:
        if user.last_active and (datetime.utcnow() - user.last_active < timedelta(minutes=1)):
            online_users.append(user)

    return render_template('main/onlineusers.html', online_users=online_users, user=current_user)


@main.before_request
def update_last_active():
    current_user.last_active = datetime.utcnow()
    db.session.commit()

project/templates/main/base.html
{% extends "base.html" %}
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">User Menu</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
	    </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                     <a class="nav-link" href="{{ url_for('main.home') }}">Home Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.user_list') }}">User Info</a>
                </li>
                {% if user.manager %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user_create') }}">Create User</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.online_users') }}">Online Users</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
	        </ul>
        </div>
    </nav>
{% endblock %}

project/templates/main/home.html
{% extends "main/base.html" %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
    <h1>Welcome, {{ user.username }}!</h1>
    <div class="wrapper">
       <img src="{{ url_for('static', filename='gibrowalker.png' ) }}" class="img-responsive" alt="Responsive image">
    </div>
{% endblock %}

project/templates/main/onlineusers.html
{% extends "main/base.html" %}

{% if user.manager %}
    {% block title %}
        Online Users
    {% endblock %}


    {% block content %}
        <div class="container">
          <h1>Online Users</h1>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Username</th>
                <th>IPadress</th>
                <th>Login Date-Time</th>
              </tr>
            </thead>
            <tbody>
                {% for user in online_users %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ request.environ.get('HTTP_X_REAL_IP', request.remote_addr) }} </td>
<!--                        <td>{{ request.access_route }} </td>-->
                        <td>{{ user.last_login.strftime('%d-%b-%Y-%H:%M:%S') }}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
    {% endblock %}

{% endif %}

project/templates/main/user_create.html
{% if user.manager %}
    {% extends "main/base.html" %}
{% else %}
    {% extends "authentication/base.html" %}
{% endif %}

{% block title %}
    {% if user.manager %}
        Create User
    {% else %}
        Sign Up
    {% endif %}
{% endblock %}

{% block content %}
{% if user.manager %}
    <h3>Create User</h3>
{% else %}
    <h3>Sign Up</h3>
{% endif %}

<form method="post">
	<p>
        <label for="username">Username:</label>
        <input type="text" name="username">
    </p>
    <p>
        <label for="firstname">First Name:</label>
        <input type="text" name="firstname">
    </p>
    <p>
        <label for="middlename">Middle Name:</label>
        <input type="text" name="middlename">
    </p>
    <p>
        <label for="lastname">Last Name:</label>
        <input type="text" name="lastname">
    </p>
    <p>
        <label for="birthdate">Birthdate:</label>
        <input type="date" name="birthdate">
    </p>
    <p>
        <label for="email">Email:</label>
        <input type="email" name="email">
    </p>
    <p>
        <label for="password1">Password:</label>
        <input type="password" id="password1" name="password1">
    </p>
    <p>
        <label for="password2">Confirm Password:</label>
        <input type="password" id="password2" name="password2">
    </p>
    <p>
        {% if user.manager %}
            <button type="submit">Create User</button>
        {% else %}
            <button type="submit">Sign Up</button>
        {% endif %}
    </p>
</form>
{% endblock %}

project/templates/main/user_list.html
{% extends "main/base.html" %}

{% block title %}
    {% if user.manager %}
        User List
    {% else %}
        User Info
    {% endif %}
{% endblock %}

{% block content %}
    <style>
        /* Style for the "Blue" button */
        .blue-button {
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        /* Style for the "Delete User" button */
        .delete-user-button {
            padding: 5px 10px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>

        <div class="container">
          <h1 class="title">User List</h1>
          <table class="table table-hover">
            <thead>
              <tr>
                  <th>ID</th><th>Username</th>
                  <th>Firstname</th><th>Middlename</th><th>Lastname</th>
                  <th>Birthdate</th>
                  <th>Email</th>
                  <th>Password</th>
              </tr>
            </thead>
            <tbody>
             {% if user.manager %}
                {% for usr in users %}
                <tr>
                    <td>#{{ usr.id }}</td><td>{{ usr.username }}</td>
                    <td>{{ usr.firstname }}</td><td>{% if usr.middlename %} {{ usr.middlename }}{% endif %}</td><td>{{ usr.lastname }}</td>
                    <td>{{ usr.birthdate.strftime('%Y-%m-%d') }}</td>
                    <td>{{ usr.email }}</td>
<!--                    <td>{{ user.password }}</td>-->
                    <td>
                        <span id="password_{{ usr.id }}" class="password" style="display:none;">{{ usr.password }}</span>
                        <button  onclick="togglePassword('password_{{ usr.id }}')">Password</button>
                    </td>
                    <td>
                        <form method="POST" action="{{ url_for('main.user_delete', id=usr.id) }}">
                            <input type="submit" value="Delete User" class="delete-user-button"
                                   onclick="return confirm('Are you sure you want to delete this entry?')">
                        </form>
                    </td>
                    <td>
                        {% if usr.manager == False %}
                            <form method="GET" action="{{ url_for('main.user_update', idx=usr.id) }}">
                                <input type="submit" value="Update User" class="blue-button">
                            </form>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
             {% else %}
                <tr>
                    <td>#{{ user.id }}</td><td>{{ user.username }}</td>
                    <td>{{ user.firstname }}</td><td>{% if user.middlename %} {{ user.middlename }}{% endif %}</td><td>{{ user.lastname }}</td>
                    <td>{{ user.birthdate.strftime('%Y-%m-%d') }}</td>
                    <td>{{ user.email }}</td>
<!--                    <td>{{ user.password }}</td>-->
                    <td>
                        <span id="password_{{ user.id }}" class="password" style="display:none;">{{ user.password }}</span>
                        <button  onclick="togglePassword('password_{{ user.id }}')">Password</button>
                    </td>
                    <td>
                        <form method="POST" action="{{ url_for('main.user_delete', id=user.id) }}">
                            <input type="submit" value="Delete User" class="delete-user-button"
                                   onclick="return confirm('Are you sure you want to delete this entry?')">
                        </form>
                    </td>
                    <td>
                        {% if user.manager == False %}
                            <form method="GET" action="{{ url_for('main.user_update', idx=user.id) }}">
                                <input type="submit" value="Update User" class="blue-button">
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
            </tbody>
          </table>
        </div>

        <script>
            function togglePassword(id) {
                var passwordElement = document.getElementById(id);
                if (passwordElement.style.display === "none") {
                    passwordElement.style.display = "inline";
                } else {
                    passwordElement.style.display = "none";
                }
            }
        </script>
{% endblock %}

project/templates/main/user_update.html
{% extends "main/base.html" %}
{% block title %}Update User{% endblock %}
{% block content %}
<h1>Update User</h1>
<form method="post">
	<p>
        <label for="username">Username:</label>
        <input type="text" name="username" value={{user.username}}>
    </p>
    <p>
        <label for="firstname">First Name:</label>
        <input type="text" name="firstname" value={{user.firstname}}>
    </p>
    <p>
        <label for="middlename">Middle Name:</label>
        <input type="text" name="middlename" value={{user.middlename}}>
    </p>
    <p>
        <label for="lastname">Last Name:</label>
        <input type="text" name="lastname" value={{user.lastname}}>
    </p>
    <p>
        <label for="birthdate">Birthdate:</label>
        <input type="date" name="birthdate" value={{user.birthdate}}>
    </p>
    <p>
        <label for="email">Email:</label>
        <input type="email" name="email" value={{user.email}}>
    </p>
    <p>
        <button type="submit">Update User</button>
    </p>
</form>
{% endblock %}